# Permalinks
permalink:        pretty

# Your site's full URL, e.g. "https://my-site.com"
# url:

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          ''

# Site settings
title: Your Title Here
description: > # this means to ignore newlines until "baseurl:"
  Your site description here.

author:
  name:    'Esther'
  twitter: mindpl_ace
  github:  mindplace

  # This photo will be used in the about section
  photo:   http://estherleytush.com/assets/images/headshot.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    Your author description here.

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true

# Adding static pages through `_static/` folder
include: ['_static']
